apiVersion: batch/v1
kind: Job
metadata:
  name: rest-test
  namespace: twint
spec:
  template:
    spec:
      containers:
      - name: rest-test
        image: 985266629220.dkr.ecr.eu-central-1.amazonaws.com/greenfield_container_repo:test-latest
        imagePullPolicy: Always
        env:
          - name: RUNNING_ON_K8S
            value: 'yes'
      restartPolicy: Never
  backoffLimit: 1